apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-native
  labels:
    app: cloud-native
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: cloud-native
        tier: service
    spec:
      containers:
      - name: cloud-native
        image: "zhanat87/cloud-native:1.2.0"
        ports:
          - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 5